### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'sportsbet/_version.py'

### ISSUE THREAD

**Issue by timforgach** [AlgoWit/sports-betting#1]
FileNotFoundError: [Errno 2] No such file or directory: 'sportsbet/_version.py'

Getting this error when trying to setup. Any ideas as to why? I don't see any _version.py in the file structure.

**Comment by georgedouzas** [comment]
The package is broken at the moment and under heavy development. There will be shortly a fully working updated version with documentation, examples etc.

**Comment by georgedouzas** [comment]
You may use the latest release.
